action:
  title: extrahosts
  description: Test passing additional entries to container's /etc/hosts
  image: test:latest
  extra_hosts:
    - "host.docker.internal:host-gateway"
    - "example.com:127.0.0.1"
  build:
    context: ./
    tags:
      - test:latest
  command:
    - sh
    - /action/main.sh
